/** Spec 06 §2 parity locations. Acceptance evidence is in reports/06-implementation.md. */
export const PHASE6_NOTCH_PARITY = [
  {
    id: "NT1",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/renderer/lib/notify.ts#notifyAttention",
    owner: "phase-6",
  },
  {
    id: "NT2",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/main/index.ts#appOperations",
    owner: "phase-6",
  },
  {
    id: "NT3",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/main/index.ts#notifyTaskRunningInBackground",
    owner: "phase-6",
  },
  {
    id: "NT4",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/main/notch/controller.ts#NotchController",
    owner: "phase-6",
  },
  {
    id: "NT5",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/renderer/lib/sound.ts#createSoundPlayer",
    owner: "phase-6",
  },
  {
    id: "NT6",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/renderer/lib/voice/use-dictation.ts#useDictation",
    owner: "phase-6",
  },
  {
    id: "NT7",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "src/renderer/features/settings/companion.tsx#CompanionSettings",
    owner: "other-phase",
  },
] as const;
