// Self-contained: the browser smoke test loads this file directly.
import { ORPCError } from "@orpc/server";

export type HostPlatform = "electron" | "web-host";
export const WEB_HOST_DENIED = [
  "window",
  "notch",
  "devices",
  "localModels",
  "update",
  "browser",
  "system.dialog",
  "system.openExternal",
  "system.notify",
  "system.logs.save",
  "messaging.showLogin",
  "skills.importLocal",
  "mcp.oauthSignIn",
  "auth.abacus",
  "auth.openRouter.start",
  "auth.openRouter.cancel",
  "system.loginItem",
  "system.restart",
  "system.openPath",
  "system.showItemInFolder",
  "system.openPrivacyPane",
  "skills.openFile",
  "voice.whisper.fetch",
] as const;
// Exact paths: a new contract procedure requires an explicit platform decision.
export const WEB_HOST_ALLOWED = [
  "workspaces.add",
  "workspaces.ensureSessionHome",
  "workspaces.sessionHomePath",
  "workspaces.switch",
  "workspaces.checkPath",
  "workspaces.relocate",
  "git.worktrees.list",
  "git.worktrees.create",
  "git.worktrees.setForSession",
  "git.worktrees.materialize",
  "git.branches",
  "git.currentBranch",
  "git.prInfo",
  "git.switchBranch",
  "git.createBranch",
  "git.diff",
  "git.discard",
  "git.checkoutStatus",
  "git.watch",
  "files.treeRoot",
  "files.treeChildren",
  "files.search",
  "files.rename",
  "files.trash",
  "files.savePastedTemp",
  "files.readImageAsDataUrl",
  "files.readText",
  "files.readPptx",
  "files.events",
  "sessions.turnState",
  "agent.feedback",
  "agent.start",
  "agent.stop",
  "agent.state",
  "agent.setMode",
  "agent.setModel",
  "agent.reset",
  "agent.switchConversation",
  "agent.respondPermission",
  "agent.skills",
  "agent.queue.enqueue",
  "agent.queue.dequeue",
  "agent.queue.get",
  "agent.queue.clear",
  "agent.queue.remove",
  "agent.queue.update",
  "ai.runFinished",
  "ai.attention",
  "ai.subscribe",
  "ai.send",
  "ai.react",
  "ai.hydrate",
  "ai.joinRun",
  "ai.cancel",
  "ai.respondPermission",
  "ai.queue.enqueue",
  "ai.queue.update",
  "ai.queue.remove",
  "ai.queue.clear",
  "ai.queue.dequeue",
  "bots.chatPreviews",
  "bots.senderChats",
  "bots.announceChange",
  "bots.openChat",
  "bots.events",
  "routines.editByChat",
  "routines.run",
  "routines.hostedRuns",
  "routines.runners",
  "routines.approvalLink",
  "routines.refreshHosted",
  "routines.events",
  "settings.get",
  "settings.promptHistory.list",
  "settings.promptHistory.add",
  "settings.keys.listProviders",
  "settings.keys.save",
  "settings.setDefaultModel",
  "settings.toolsets.get",
  "settings.toolsets.setEnabled",
  "settings.defaultMode.get",
  "settings.defaultMode.set",
  "settings.sandboxSupport",
  "settings.notifications.get",
  "settings.notifications.set",
  "settings.execBackend.get",
  "settings.execBackend.set",
  "settings.events",
  "models.list",
  "account.usage",
  "account.abacus",
  "account.vaultUrl",
  "account.state",
  "account.skipOnboarding",
  "account.signOut",
  "account.forget",
  "auth.web.start",
  "auth.web.complete",
  "referrals.summary",
  "referrals.gmailContacts",
  "referrals.sendEmail",
  "referrals.whatsappContacts",
  "referrals.sendWhatsapp",
  "connectors.statuses",
  "connectors.connect",
  "connectors.cancelConnect",
  "connectors.submitFields",
  "connectors.disconnect",
  "connectors.respond",
  "connectors.requests",
  "connectors.events",
  "mcp.list",
  "mcp.add",
  "mcp.update",
  "mcp.remove",
  "mcp.setDisabled",
  "mcp.import",
  "mcp.refresh",
  "mcp.restart",
  "mcp.runtime.servers",
  "mcp.runtime.logs",
  "mcp.runtime.events",
  "terminal.start",
  "terminal.write",
  "terminal.resize",
  "terminal.hide",
  "terminal.promoteScope",
  "terminal.shell.get",
  "terminal.shell.set",
  "terminal.output",
  "terminal.events",
  "memory.customInstructions.get",
  "memory.customInstructions.set",
  "memory.forgetAll",
  "memory.bots",
  "memory.clearBot",
  "memory.events",
  "voice.whisper.progress",
  "voice.requestMicrophone",
  "messaging.snapshot",
  "messaging.updatePlatform",
  "messaging.decidePairing",
  "messaging.updateSettings",
  "messaging.pairShared",
  "messaging.unlinkShared",
  "messaging.openSharedLink",
  "messaging.events",
  "system.activity",
  "system.info",
  "system.acknowledgeLegacyDrafts",
  "system.funnelStep",
  "system.logs.append",
  "system.events",
  "skills.listInstalled",
  "skills.search",
  "skills.install",
  "skills.remove",
  "db.sessions.snapshot",
  "db.sessions.changes",
  "db.sessions.insert",
  "db.sessions.update",
  "db.sessions.delete",
  "db.bots.snapshot",
  "db.bots.changes",
  "db.bots.insert",
  "db.bots.update",
  "db.bots.delete",
  "db.routines.snapshot",
  "db.routines.changes",
  "db.routines.insert",
  "db.routines.update",
  "db.routines.delete",
  "db.routineRuns.snapshot",
  "db.routineRuns.changes",
  "db.artifacts.snapshot",
  "db.artifacts.changes",
  "db.memories.snapshot",
  "db.memories.changes",
  "db.memories.delete",
  "db.workspaces.snapshot",
  "db.workspaces.changes",
  "db.workspaces.update",
  "db.workspaces.delete",
  "db.gitState.snapshot",
  "db.gitState.changes",
  "db.prefs.snapshot",
  "db.prefs.changes",
  "db.prefs.update",
] as const;
export const supportsProcedure = (
  platform: HostPlatform,
  procedure: string,
  input?: unknown
): boolean =>
  platform === "electron" ||
  (WEB_HOST_ALLOWED.some((path) => path === procedure) &&
    !(
      procedure === "mcp.import" &&
      (input as { source?: string } | undefined)?.source === "file"
    ));

export const assertHostCapability = (
  platform: HostPlatform,
  procedure: string,
  input?: unknown
): void => {
  if (!supportsProcedure(platform, procedure, input))
    throw new ORPCError("UNSUPPORTED", { status: 501, data: { procedure } });
};
