/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./notch-routes/__root"
import { Route as CallRouteImport } from "./notch-routes/call"
import { Route as DoneRouteImport } from "./notch-routes/done"
import { Route as FailedRouteImport } from "./notch-routes/failed"
import { Route as IdleRouteImport } from "./notch-routes/idle"
import { Route as WorkingRouteImport } from "./notch-routes/working"
import { Route as ApprovalIdRouteImport } from "./notch-routes/approval.$id"
import { Route as ReplyIdRouteImport } from "./notch-routes/reply.$id"

const CallRoute = CallRouteImport.update({
  id: "/call",
  path: "/call",
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: "/done",
  path: "/done",
  getParentRoute: () => rootRouteImport,
} as any)
const FailedRoute = FailedRouteImport.update({
  id: "/failed",
  path: "/failed",
  getParentRoute: () => rootRouteImport,
} as any)
const IdleRoute = IdleRouteImport.update({
  id: "/idle",
  path: "/idle",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkingRoute = WorkingRouteImport.update({
  id: "/working",
  path: "/working",
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalIdRoute = ApprovalIdRouteImport.update({
  id: "/approval/$id",
  path: "/approval/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyIdRoute = ReplyIdRouteImport.update({
  id: "/reply/$id",
  path: "/reply/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/call": typeof CallRoute
  "/done": typeof DoneRoute
  "/failed": typeof FailedRoute
  "/idle": typeof IdleRoute
  "/working": typeof WorkingRoute
  "/approval/$id": typeof ApprovalIdRoute
  "/reply/$id": typeof ReplyIdRoute
}
export interface FileRoutesByTo {
  "/call": typeof CallRoute
  "/done": typeof DoneRoute
  "/failed": typeof FailedRoute
  "/idle": typeof IdleRoute
  "/working": typeof WorkingRoute
  "/approval/$id": typeof ApprovalIdRoute
  "/reply/$id": typeof ReplyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/call": typeof CallRoute
  "/done": typeof DoneRoute
  "/failed": typeof FailedRoute
  "/idle": typeof IdleRoute
  "/working": typeof WorkingRoute
  "/approval/$id": typeof ApprovalIdRoute
  "/reply/$id": typeof ReplyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/call"
    | "/done"
    | "/failed"
    | "/idle"
    | "/working"
    | "/approval/$id"
    | "/reply/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/call"
    | "/done"
    | "/failed"
    | "/idle"
    | "/working"
    | "/approval/$id"
    | "/reply/$id"
  id:
    | "__root__"
    | "/call"
    | "/done"
    | "/failed"
    | "/idle"
    | "/working"
    | "/approval/$id"
    | "/reply/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CallRoute: typeof CallRoute
  DoneRoute: typeof DoneRoute
  FailedRoute: typeof FailedRoute
  IdleRoute: typeof IdleRoute
  WorkingRoute: typeof WorkingRoute
  ApprovalIdRoute: typeof ApprovalIdRoute
  ReplyIdRoute: typeof ReplyIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/call": {
      id: "/call"
      path: "/call"
      fullPath: "/call"
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/done": {
      id: "/done"
      path: "/done"
      fullPath: "/done"
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/failed": {
      id: "/failed"
      path: "/failed"
      fullPath: "/failed"
      preLoaderRoute: typeof FailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/idle": {
      id: "/idle"
      path: "/idle"
      fullPath: "/idle"
      preLoaderRoute: typeof IdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/working": {
      id: "/working"
      path: "/working"
      fullPath: "/working"
      preLoaderRoute: typeof WorkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/approval/$id": {
      id: "/approval/$id"
      path: "/approval/$id"
      fullPath: "/approval/$id"
      preLoaderRoute: typeof ApprovalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reply/$id": {
      id: "/reply/$id"
      path: "/reply/$id"
      fullPath: "/reply/$id"
      preLoaderRoute: typeof ReplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CallRoute: CallRoute,
  DoneRoute: DoneRoute,
  FailedRoute: FailedRoute,
  IdleRoute: IdleRoute,
  WorkingRoute: WorkingRoute,
  ApprovalIdRoute: ApprovalIdRoute,
  ReplyIdRoute: ReplyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
