/** Spec §2 inventory. Partial means implementation exists but full acceptance has not been demonstrated. */
export const SESSION_PARITY = [
  {
    id: "S1",
    requirement:
      "`/sessions/new` → `SessionStartPage` (§8); the workspace comes from `?workspace=` or `prefs.lastPickedWorkspaceId` (§8.3)",
    decision: "Parity; intent and deselect retired (routes carry ids)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S2",
    requirement:
      "loader: awaits `sessions`/`workspaces` readiness, row or `notFound()`; on enter (not preload) unread cleared, `session.load()` (§5.3); every file/git call carries the session's checkout (F5)",
    decision:
      "Changed: the workspace switch is retired (checkout-aware APIs, §26.4)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S3",
    requirement:
      "route `pendingComponent`: transcript skeleton (foundation `defaultPendingMs` 150)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S4",
    requirement:
      '`notFoundComponent` "This session was deleted" + New session (§5.5)',
    decision: "Changed (gap fix)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S5",
    requirement:
      "`/` → `/bots/new` (foundation); side panel state is `?tab=` only",
    decision:
      'Retired (PLAN "Nuked: `?view=` redirects"; "no state in two places")',
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S6",
    requirement: '`<AppLink to="/sessions/$sessionId">`',
    decision: "Changed: no switch (F5)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S7",
    requirement: "`useParams({ strict: false }).sessionId`",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S8",
    requirement:
      "`/sessions/$sessionId/review` → `?tab=changes` redirect (F3); `/sessions/$sessionId/diff` masked full-diff dialog (§5.4)",
    decision: "New",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S9",
    requirement:
      'one sidebar for the Sessions rail item, header "Sessions" + Search + New (canvas `SessionsSidebar`)',
    decision: 'Changed (user decision "one sidebar per rail item")',
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S10",
    requirement:
      "same filter; grouped by workspace (foundation §7.3; canvas) (§7.2)",
    decision: "Changed (canvas, foundation)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S11",
    requirement:
      "inside a workspace group rows are ordered by `updatedAt` desc with no bucket headers; the search results and the collapsed-sidebar history show a relative stamp (`chatStamp`, 03 P17)",
    decision: "Changed (canvas has no buckets)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S12",
    requirement:
      '"Pinned" group above the workspaces (`prefs.pinned.sessionIds`)',
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S13",
    requirement:
      "32 px row (34 in the tree board): status dot, label, trailing chip (running / needs you / diff / unread); pin shown by group (§7.3)",
    decision: "Parity + New (status)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S14",
    requirement: 'running dot + "running", "needs you" chip, error (§6.6)',
    decision: "New (canvas; dead `workspace-tree.tsx` had dots)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S15",
    requirement: 'same (`scrollIntoView({ block: "nearest" })`)',
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S16",
    requirement: 'link to `/sessions/$sessionId`, `transition: "nav-lateral"`',
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S17",
    requirement:
      "one item list for both menus: Rename, Pin/Unpin, Mark as unread, Open beside this chat, New worktree from here, Copy session ID, Delete session (§7.4)",
    decision: "Parity + New",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S18",
    requirement:
      "registry `AlertDialog`, same copy; `agent.stop` then `sessionsCollection.delete` (§6.4); inline error",
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S19",
    requirement:
      'canvas: "No sessions yet" / "Start one with ⌘N, or drop a folder here." + drop zone (§7.6)',
    decision: "Parity + New (drop)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S20",
    requirement:
      'Search field with highlighted matches and "workspace · branch" sub-line (canvas) (§7.1)',
    decision: "New",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S21",
    requirement:
      "Workspace group: collapsible (`prefs.workspaceExpanded`), count, branch, missing state, row menu (§7.5)",
    decision: "New in production (dead code had grouping)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S22",
    requirement:
      "inline rename from the row menu and the title bar (§7.4, §9.1); automatic title stays in the kit (02 §8.3)",
    decision: "Parity + New",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S23",
    requirement: "`prefs.pinned.sessionIds` (spec 00 C.4 imports it)",
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S24",
    requirement:
      "`sessionsUnreadStore` over `ai.runFinished` (`success`/`error`; a Stop marks nothing) (§6.7)",
    decision: "Parity (cancellation no longer marks unread)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S25",
    requirement:
      "same rule on `browser.events runtime-materialized` (§6.7, §12.6)",
    decision: "Parity",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S26",
    requirement: "foundation `Mod+B`",
    decision: "Parity (foundation)",
    target: "features/sessions/sessions-sidebar.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/sessions-sidebar.tsx#groupSessions",
  },
  {
    id: "S27",
    requirement:
      'canvas `Main`: "What should we build?", 120 px two-row box ("Describe the work. Type @ for files, / for skills"), context tray under it (§8.1)',
    decision: "Changed (canvas)",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S28",
    requirement:
      "tray workspace button → `WorkspacePicker` popover: same rows, search, Default workspace, Add a folder (§8.3)",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S29",
    requirement:
      "`system.dialog.openFolder()` → `workspaces.add({ path })`; typed errors (§6.5); picks it",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S30",
    requirement:
      "same order in the start page's loader (§8.3); `prefs.lastPickedWorkspaceId`",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S31",
    requirement:
      'canvas starter cards (3 × 2, "Try one of these", Shuffle); same fill-and-focus (§8.4)',
    decision: "Parity (canvas geometry)",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S32",
    requirement:
      'sidebar collapsed: "Pick up where you left off in {workspace}" list of 4 recent sessions beside starters (canvas `MainCollapsed`) (§8.5)',
    decision: "New",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S33",
    requirement:
      'tray worktree button (canvas "New worktree" / "No worktree") with the same options (§8.3)',
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S34",
    requirement:
      "kit `ModeChip` (02 §8.2); Auto hidden without sandbox support; default from `prefs.defaultMode`, written on change (§9.3)",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S35",
    requirement:
      'kit `ModelChip` with the groups of 03 §13.1 (shared builder); same resolution; "Compact UI" retired (§9.3)',
    decision:
      "Parity; Compact UI retired (density is a window-chrome setting now)",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S36",
    requirement:
      'composer `blocked` reason "no-model" + the same CTA (§26.2 kit amendment)',
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S37",
    requirement:
      "`startSession()` (§8.6): client id, insert, worktree, `promoteScope` for terminal and browser, navigate, first message submitted by the thread",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S38",
    requirement:
      "kit attachments with `attachmentsBase` = workspace or worktree path (02 §8.6)",
    decision: "Parity (kit)",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S39",
    requirement:
      "start page resolves a workspace before enabling Send; missing folder → the workspace-missing state (§17.2)",
    decision: "Parity",
    target: "features/sessions/start/session-start-page.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/start/session-start-page.tsx#SessionStartPage",
  },
  {
    id: "S40",
    requirement:
      '`TopBarSlot identity`: "{workspace} /" (muted) + label (500), click to rename (§9.1)',
    decision: "Parity + New (rename)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S41",
    requirement:
      "New session (`Mod+N`, foundation), panel toggle (foundation), tab strip when open (§10.1); terminal toggle retired (F16)",
    decision: "Parity; terminal toggle changed",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S42",
    requirement:
      "`ensureAgentStarted(row)` on enter, same schedule; failure → thread banner with Retry (not a toast, R4-T8) (§9.2)",
    decision: "Parity (banner instead of toast)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S43",
    requirement: "after a successful start, once (§9.2)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S44",
    requirement:
      "`sessionsCollection.update({model})` + `agent.setModel` when running + `settings.setDefaultModel` (§9.3); same toast",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S45",
    requirement: "kit `ModeChip` (02 §8.2) + `prefs.defaultMode` write",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S46",
    requirement:
      'kit `ChatView skin="session"` (02 §5, §10); pending first message = outbox (02 §3.7)',
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S47",
    requirement: "kit queue slot (02 §8.5)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S48",
    requirement: "kit Stop = `ai.cancel` (02 §4.5)",
    decision:
      "Changed: retraction and empty-session deletion retired (the agent echoes and persists the user message on admission, 02 F3; deleting is explicit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S49",
    requirement: "kit admission outcomes (02 §3.7, §4.6)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S50",
    requirement: "kit `deriveSessionTitle` (02 §8.3)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S51",
    requirement: "kit `Notice`, `ErrorCard` (02 §5.6)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S52",
    requirement:
      'the feedback popover of 03 §11.3, enabled for `skin="session"` too (§26.2)',
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S53",
    requirement: "kit (03 P65)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S54",
    requirement:
      "kit composer: ArrowUp walks history when the queue is empty, from a route-supplied `history` source over `settings.promptHistory.*` (§26.2)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S55",
    requirement: "kit `mentions` from this route: `files.search` (§9.3)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S56",
    requirement: 'tray "Tasks {done} of {n}" opening the plan popover (§9.4)',
    decision: "Parity (canvas)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S57",
    requirement:
      "tray branch button → `BranchPicker` popover, same rules and copy (§14.2)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S58",
    requirement:
      "tray PR item + hover card, `git.prInfo` with `refetchInterval: 60_000` and focus refetch (§14.3)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S59",
    requirement:
      "kit permission tray (02 §6); auto-resolve on a more permissive mode is main/agent behaviour (00-agent-agui §3.5)",
    decision: "Parity (kit)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S60",
    requirement:
      "`features/sessions/notify.ts` via `system.notify` + `system.events notification-clicked` (§19.2)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S61",
    requirement:
      "`BrowserAskHost` mounted by the shell, `browser.events` + `browser.permissions.respond` (§12.7)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S62",
    requirement:
      'read-only composer banner (canvas `ReadOnlyStates` "A session whose folder is gone") (§17.3)',
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S63",
    requirement:
      "canvas `SessionWorkspaceMissing` pane state with Choose folder / Delete workspace, and the send-blocked composer line (§17.2); dismissal retired (the state is inline, not a dialog)",
    decision: "Parity; dialog → inline",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S64",
    requirement:
      'read-only session skin with the routines banner and "Talk to the routine" (phase 5 route) (§17.3)',
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S65",
    requirement:
      "the shared `components/connector-request-card/` of 03 r3 §11.4 in the session's `slots.banner`, fed by `connectors.events({ conversationKey })` (snapshot of pending asks first), field flows via `connectors.submitFields`, decline, `connectors.respond` clearing the card (the turn never waits on it)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S66",
    requirement:
      "kit composer drop (02 §8.6) over the whole thread pane (the route forwards `onDrop`)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S67",
    requirement:
      'kit `DiffExpander` (02 §5.4); "Open full diff" → `/sessions/$id/diff` (§5.4)',
    decision: "Parity (kit) + New (full diff)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S68",
    requirement: "kit `SubagentCard` + Agents tab detail (§15)",
    decision: "Parity",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S69",
    requirement:
      '`ChangesCard` in `RunTail`: "{n} files changed +a −d", Review changes (canvas `SessionRunning`, `SessionReview`) (§9.5)',
    decision: "New",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S70",
    requirement:
      "`panelTabsStore` per conversation key (open tabs) + `?tab=` (active) (§10.2); same neighbour rule",
    decision: "Parity",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S71",
    requirement:
      '"Add a tab" menu, same items and rules; Changes added when there are changes (§10.1)',
    decision: "Parity + New (Changes)",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S72",
    requirement:
      "no empty panel: the strip exists only while a tab is open (user decision); the toggle opens the last tab or the menu (§10.1)",
    decision: "Changed (user decision)",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S73",
    requirement:
      "same: `<Activity mode>` per tab, browser presented only when visible (§10.5)",
    decision: "Parity",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S74",
    requirement: "same (§10.1)",
    decision: "Parity",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S75",
    requirement:
      "chat pane default 480 (canvas), min 360; panel min 360; persisted in `prefs.panes` (§10.3)",
    decision: "Changed (canvas + foundation minimums)",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S76",
    requirement:
      "below 1100 the pane folds into one tab strip with Chat first (F4)",
    decision: "Changed (canvas `W900`)",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S77",
    requirement: "`preview:<key>` tabs, same cap and eviction (§13.3)",
    decision: "Parity",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S78",
    requirement: '`@tanstack/highlight` viewer + "Open in editor" (§13.3)',
    decision: 'Changed (PLAN "Editing / Nuked: monaco")',
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S79",
    requirement: "same viewers (`components/file-preview/`) (§13.3)",
    decision: "Parity",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S80",
    requirement:
      "a guarded **local-file runtime** tab on the native surface (F8, §12.8, main amendment §26.4 f)",
    decision: "Parity (mechanism changed)",
    target: "features/sessions/dock/session-dock.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/dock/session-dock.tsx#SessionDock",
  },
  {
    id: "S81",
    requirement:
      "same engine and options; theme from tokens for both schemes (§11.2)",
    decision: "Parity + light theme",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S82",
    requirement: "open a Browser tab (§11.2)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S83",
    requirement: "ported verbatim with its tests (§11.4)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S84",
    requirement: "ported verbatim (§11.4)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S85",
    requirement:
      "one side-panel tab per terminal, same id scheme and labels (§11.1)",
    decision: "Changed (F16)",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S86",
    requirement: '"New terminal" split button with the shell menu (§11.1)',
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S87",
    requirement:
      'tab close = kill, no confirmation (parity); switching away = `hide`; exit → the tab shows "Process exited with code {n}" for 2 s, then closes (§11.1)',
    decision: "Parity + exit notice",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S88",
    requirement: "same (`terminal-registry.ts`) (§11.3)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S89",
    requirement:
      "`terminal.output` with `fromOffset`; `snapshot` append vs replace by `from` (§11.3)",
    decision: "Changed (lossless offsets)",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S90",
    requirement: "same, pacer-debounced 40 ms (§11.3)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S91",
    requirement: "same (§11.3)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S92",
    requirement:
      "`terminal.promoteScope` + re-key; `retired {superseded}` ends the old iterator (§11.1)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S93",
    requirement: "same (§11.1)",
    decision: "Parity",
    target: "features/sessions/terminal/terminal-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/terminal/terminal-tab.tsx#TerminalTab",
  },
  {
    id: "S94",
    requirement: "same contract (§12.2–§12.4)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S95",
    requirement: "same (`normalizeAddress` ported with tests) (§12.5)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S96",
    requirement: "same items (§12.5)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S97",
    requirement: "same (§12.5)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S98",
    requirement: "foundation occlusion watcher + intersect test (§12.4)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S99",
    requirement: "same on `browser.events` (§12.1, §12.6)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S100",
    requirement: "`browser.runtime.close(lease)` (§12.3)",
    decision: "Parity",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S101",
    requirement: "—",
    decision: "Retired (unused)",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "retired",
    status: "retired",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S102",
    requirement:
      '"The agent is browsing. Take over / I\'m done" bar (canvas `SessionBrowser`)',
    decision:
      "Deferred: no take-over procedure (§27.3); the bar renders the status line only",
    target: "features/sessions/browser/browser-tab.tsx",
    implementation: "deferred",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/browser/browser-tab.tsx#normalizeAddress",
  },
  {
    id: "S103",
    requirement:
      'same library and behaviour; canvas "Filter files" field and "M" marks (§13.1)',
    decision: "Parity + New (filter)",
    target: "features/sessions/files/files-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/files/files-tab.tsx#flattenFiles",
  },
  {
    id: "S104",
    requirement: "same (§13.2)",
    decision: "Parity",
    target: "features/sessions/files/files-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/files/files-tab.tsx#flattenFiles",
  },
  {
    id: "S105",
    requirement: "same + Open in editor (§13.2)",
    decision: "Parity + New",
    target: "features/sessions/files/files-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/files/files-tab.tsx#flattenFiles",
  },
  {
    id: "S106",
    requirement: "same; `files.events tree-root-changed` + `gitState` (§13.1)",
    decision: "Parity",
    target: "features/sessions/files/files-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/files/files-tab.tsx#flattenFiles",
  },
  {
    id: "S107",
    requirement:
      "Changes tab: changed files, per-file diff, Keep, Undo (with §26.4), change navigation (canvas `SessionReview`) (§14)",
    decision: "New",
    target: "features/sessions/changes/changes-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/changes/changes-tab.tsx#changeRows",
  },
  {
    id: "S108",
    requirement: "Agents tab list + detail (canvas `SubAgents`) (§15)",
    decision: "Parity (detail replaces transcript scoping)",
    target: "routes/_shell/(sessions)/sessions.$sessionId.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/routes/_shell/(sessions)/sessions.$sessionId.tsx#Route",
  },
  {
    id: "S109",
    requirement: "Device tab, same controls (§16)",
    decision: "Parity",
    target: "features/sessions/device/device-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/device/device-tab.tsx#DeviceTab",
  },
  {
    id: "S110",
    requirement: "ported (F9) (§16.2), fallback chain included",
    decision: "Parity",
    target: "features/sessions/device/device-tab.tsx",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer: "apps/web/src/features/sessions/device/device-tab.tsx#DeviceTab",
  },
  {
    id: "S111",
    requirement: "`SessionPreviewBridge` mounted once by the shell (§13.4)",
    decision: "Parity",
    target: "features/sessions/files/preview-bridge.ts",
    implementation: "partial",
    status: "deferred",
    visible: false,
    reason: "Acceptance remains open in the phase-4 report.",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    consumer:
      "apps/web/src/features/sessions/files/preview-bridge.ts#recordBackgroundPreview",
  },
] as const;
