/** Spec §2 inventory. Partial rows are explained in the implementation report. */
export const PHASE5_PARITY = [
  {
    id: "AR1",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (PLAN rail)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR2",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity + New (sort)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR3",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (matching changed to substring)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR4",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR5",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR6",
    status: "retired",
    target: "features/artifacts/index.tsx",
    specStatus: "Retired (live data)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR7",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (canvas copy)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR8",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR9",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (canvas)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR10",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (canvas: preview in Artifacts, not in the session)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR11",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: 'Changed (canvas `ArtifactsPreview`: "Open in browser")',
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR12",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity + New (bot and routine targets)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR13",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR14",
    status: "implemented",
    target: "features/artifacts/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR15",
    status: "partial",
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (Remove deferred)",
    consumer: "src/renderer-next/features/artifacts/index.tsx#ArtifactsSidebar",
  },
] as const;
