/** Spec §2 inventory. Partial rows are explained in the implementation report. */
export const PHASE5_PARITY = [
  {
    id: "ST1",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Changed (canvas, user decision)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST2",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Changed (foundation)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST3",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: 'Changed (PLAN "Nuked: `staticData.titleKey`")',
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST4",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST5",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity + System option (foundation \u00a79.2)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST6",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity (canvas)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST7",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Changed (canvas placement)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST8",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity + confirm",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST9",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Changed (canvas)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST10",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity (canvas placement)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST11",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST12",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity + confirm",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST13",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus:
      "Changed (PLAN Sound, F12); the old sound opt-out is imported (\u00a731.5 i)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST14",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST15",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity (canvas layout)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST16",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST17",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity + New (install)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST18",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus:
      "Parity + New (manual check, About); composer strip and home banner Retired (canvas: pill + About cover them)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST19",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST20",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Changed (canvas)",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST21",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST22",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Deferred to phase 6",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST23",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST24",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST25",
    status: "implemented",
    target: "features/settings/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST26",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "New",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
  {
    id: "ST27",
    status: "partial",
    target: "features/settings/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/settings/index.tsx#SettingsSidebar",
  },
] as const;
