/** §2 parity inventory. Partial rows name dependencies in the phase-3 report. */
export const BOT_PARITY = [
  {
    id: "P1",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P2",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Parity; workspace switch retired (PLAN)",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P3",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P4",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Changed (gap fix)",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P5",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Changed (PLAN route tree)",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P6",
    status: "implemented",
    target: "routes/_shell/(bots)/bots.$botId.tsx",
    specStatus: "Changed (gap fix)",
    consumer: "src/renderer-next/routes/_shell/(bots)/bots.$botId.tsx#Route",
  },
  {
    id: "P7",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P8",
    status: "retired",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Retired (F15)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P9",
    status: "retired",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Retired (canvas)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P10",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Changed (canvas BotDetails)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P11",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "New",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P12",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Changed (F8)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P13",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity; count retired (canvas)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P14",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Changed (needs-you group, PLAN)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P15",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P16",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity (canvas geometry)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P17",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P18",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity + canvas",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P19",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P20",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P21",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity + New (Mark as unread, Duplicate, Pause)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P22",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Changed (bug fix)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P23",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Changed (PLAN)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P24",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P25",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P26",
    status: "retired",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Retired (F15)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P27",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "New",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P28",
    status: "implemented",
    target: "features/bots/sidebar/bots-sidebar.tsx",
    specStatus: "Parity with foundation",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
  {
    id: "P29",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity (canvas geometry)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P30",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity + New (marks)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P31",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P32",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P33",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P34",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity; max added (gap fix)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P35",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Changed (gap fix)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P36",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P37",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P38",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity + New (accessory)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P39",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P40",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P41",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus:
      "Parity; custom display changed (gap fix, value still untouched)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P42",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P43",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P44",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: 'Changed (PLAN "Bot model")',
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P45",
    status: "implemented",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Parity (hook only)",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P46",
    status: "deferred",
    target: "features/bots/form/bot-form.tsx",
    specStatus: "Deferred to phase 6",
    consumer: "src/renderer-next/features/bots/form/bot-form.tsx#BotSetupForm",
  },
  {
    id: "P47",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P48",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P49",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P50",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P51",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity (kit)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P52",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P53",
    status: "partial",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity (URL preview needs phase 4's browser surface, §24.13)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P54",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity (kit)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P55",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P56",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P57",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P58",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity (kit)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P59",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P60",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity + New (button)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P61",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity; Revoke moves",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P62",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P63",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P64",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Changed (canvas BotApproval, 02)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P65",
    status: "implemented",
    target: "features/bots/chat/slots.tsx",
    specStatus: "Parity (kit)",
    consumer: "src/renderer-next/features/bots/chat/slots.tsx#useBotChatSlots",
  },
  {
    id: "P66",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "Parity + New (entry point)",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#MemoryTab",
  },
  {
    id: "P67",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#MemoryTab",
  },
  {
    id: "P68",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#MemoryTab",
  },
  {
    id: "P69",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#DetailsTab",
  },
  {
    id: "P70",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "Parity",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#DetailsTab",
  },
  {
    id: "P71",
    status: "implemented",
    target: "components/bot-avatar/index.tsx",
    specStatus: 'Changed (PLAN "Nuked")',
    consumer: "src/renderer-next/components/bot-avatar/index.tsx#BotAvatar",
  },
  {
    id: "P72",
    status: "implemented",
    target: "features/bots/panel/bot-side-panel.tsx",
    specStatus: "New",
    consumer:
      "src/renderer-next/features/bots/panel/bot-side-panel.tsx#FilesTab",
  },
  {
    id: "P73",
    status: "implemented",
    target: "components/bot-avatar/index.tsx",
    specStatus: "New (PLAN)",
    consumer:
      "src/renderer-next/features/bots/sidebar/bots-sidebar.tsx#BotsSidebar",
  },
] as const;
