/** Spec §2 inventory. Partial rows are explained in the implementation report. */
export const PHASE5_PARITY = [
  {
    id: "AR1",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (PLAN rail)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR2",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity + New (sort)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR3",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (matching changed to substring)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR4",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR5",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "New",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR6",
    status: "retired",
    reason: "Artifacts refresh automatically; the Refresh button is removed.",
    visible: true,
    target: "features/artifacts/index.tsx",
    specStatus: "Retired (live data)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR7",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (canvas copy)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR8",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR9",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (canvas)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR10",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Changed (canvas: preview in Artifacts, not in the session)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR11",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: 'Changed (canvas `ArtifactsPreview`: "Open in browser")',
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR12",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity + New (bot and routine targets)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR13",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR14",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "New",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
  {
    id: "AR15",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/artifacts/index.tsx",
    specStatus: "Parity (Remove deferred)",
    consumer: "apps/web/src/features/artifacts/index.tsx#ArtifactsSidebar",
  },
] as const;
