/** Spec §2 inventory. Partial rows are explained in the implementation report. */
export const PHASE5_PARITY = [
  {
    id: "RT1",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: 'Changed (user decision "one sidebar per rail item")',
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT2",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity + New (states)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT3",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Changed (03 F8: the sender-chat view is the bots route)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT4",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Changed (canvas; counts future fires too)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT5",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (canvas copy)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT6",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (canvas layout)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT7",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT8",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT9",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT10",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT11",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT12",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity + New (next-fire preview)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT13",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (typed errors, F1)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT14",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (canvas placement)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT15",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT16",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT17",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (live instead of polling)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT18",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Changed (canvas: report on demand)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT19",
    status: "retired",
    reason: "Opening a routine run keeps your current workspace.",
    visible: true,
    target: "features/routines/index.tsx",
    specStatus: 'Retired (PLAN "no state in two places")',
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT20",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (canvas)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT21",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT22",
    status: "green",
    evidence:
      "R7-T25 implementation consumer and exact-id checks; packaged acceptance remains open.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity (confirm added)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT23",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Changed (03 F8)",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT24",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT25",
    status: "deferred",
    owner: "release manager",
    plan: "docs/rewrite/PLAN.md#phases-and-pr-stack",
    reason: "Acceptance remains open in the phase report.",
    visible: false,
    target: "features/routines/index.tsx",
    specStatus: "Parity",
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
  {
    id: "RT26",
    status: "retired",
    reason:
      "Legacy /settings/jobs and /routines/chat links are retired; open Routines from the rail.",
    visible: true,
    target: "features/routines/index.tsx",
    specStatus: 'Retired (PLAN "Nuked: `?view=` redirects"; new entry HTML)',
    consumer: "src/renderer/features/routines/index.tsx#RoutinesSidebar",
  },
] as const;
