/** Spec 06 §2 parity locations. Acceptance evidence is in reports/06-implementation.md. */
export const PHASE6_ONBOARDING_PARITY = [
  {
    id: "OB1",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB2",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/routes/_shell.tsx#Route",
    owner: "phase-6",
  },
  {
    id: "OB3",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/routes/_shell.tsx#Route",
    owner: "phase-6",
  },
  {
    id: "OB4",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/machine.ts#next",
    owner: "phase-6",
  },
  {
    id: "OB5",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/machine.ts#resumeStep",
    owner: "phase-6",
  },
  {
    id: "OB6",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB7",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB8",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/store.ts#onboardingStore",
    owner: "phase-6",
  },
  {
    id: "OB9",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB10",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB11",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB12",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "OB13",
    status: "retired",
    reason:
      "Finishing setup opens the saved destination without switching a workspace.",
    visible: true,
    consumer: "apps/web/src/features/onboarding/actions.ts#completeOnboarding",
    owner: "phase-6",
  },
  {
    id: "OB14",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/actions.ts#enterStep",
    owner: "phase-6",
  },
  {
    id: "OB15",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/settings/account-usage.tsx#AccountPage",
    owner: "other-phase",
  },
  {
    id: "OB16",
    status: "retired",
    reason: "Setup no longer resets an open tour.",
    visible: true,
    consumer:
      "retired: The tour host lives only under the shell, so onboarding no longer resets an open tour.",
    owner: "phase-6",
  },
  {
    id: "OB17",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "FB1",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/first-bot.ts#firstBotStore",
    owner: "phase-6",
  },
  {
    id: "FB2",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/first-bot.ts#firstBotStore",
    owner: "phase-6",
  },
  {
    id: "FB3",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/first-bot.ts#firstBotStore",
    owner: "phase-6",
  },
  {
    id: "FB4",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/first-bot.ts#firstBotStore",
    owner: "phase-6",
  },
  {
    id: "FB5",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/stage.tsx#OnboardingStage",
    owner: "phase-6",
  },
  {
    id: "FB6",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/onboarding/index.tsx#OnboardingFrame",
    owner: "phase-6",
  },
  {
    id: "FB7",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/bots/chat/slots.tsx#useBotChatSlots",
    owner: "other-phase",
  },
  {
    id: "TR1",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR2",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR3",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR4",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR5",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR6",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR7",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR8",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
  {
    id: "TR9",
    status: "green",
    evidence: "R6-T40 located consumer; packaged acceptance remains open.",
    visible: false,
    consumer: "apps/web/src/features/tour/index.tsx#TourHost",
    owner: "phase-6",
  },
] as const;
